### ISSUE TITLE
rails_tutorial/hello_app/.gitignoreを更新する

### ISSUE THREAD

**Issue by isao0214** [junki2616/rails_tutorial#3]
## 概要

rails_tutorial/hello_app/.gitignore.gitignoreファイルがデフォルトのままなので更新する

## 方法

.gitignoreファイルを自動生成してくれるgitignore.ioというサービスを使用する
https://www.gitignore.io/

今回は、 `Ruby` , `Rails` , `Cloud9` のタグで生成する。

**Comment by junki2616** [comment]
対応済
